[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_escrow = "GeFqrkpGtzomMTAzMoDK1nFxsQaYM3xHfsGZ8dtQttwk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hetalkenaudekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
